(function(q,e){var r=q.NM&&q.NM.o;!r&&"function"===typeof define&&define.amd?define("nm.rules",[],function(){return e(null,q)}):(e(q,q),r&&q.NM.rules.init(r))})(this,function(q,e){function r(a){return(10>a?"0":"")+a}function h(a){var b=new Date,c=a.lineNumber?a.lineNumber+": ":"";f.log&&void 0!==e.console&&void 0!==e.console.log&&e.console.log(r(b.getHours())+":"+r(b.getMinutes())+":"+r(b.getSeconds())+"."+b.getMilliseconds()+": "+c+a)}function p(a){f.debug&&h(a)}function u(a){var b=e.localStorage&&
e.localStorage.getItem(a);b||(b=decodeURIComponent(e.document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null)&&p("getValue("+a+"): cookie fallback");return b}function A(a,b){p("setValue("+a+", "+b+")");null===b?e.localStorage?e.localStorage.removeItem(a):e.document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;":e.localStorage?e.localStorage.setItem(a,b):e.document.cookie=a+"="+encodeURIComponent(b)+
"; path=/";return b}function D(a){var b=u(a),b=parseInt(b||0,10)+1;return A(a,b)}function G(a){var b=arguments.length,c=null,d;for(d=1;d<b;d++)for(c in arguments[d])arguments[d].hasOwnProperty(c)&&(a[c]=arguments[d][c]);return a}function E(a){return"!"===a.charAt(0)?a.substring(1):a.replace(/^\s+|\s+$/g,"").replace(/([\\])(?=[^*]|$)/g,"\\$1").replace(/([.+?=!:${}()|\^\[\]\/])/g,"\\$1").replace(/([^\\]|^)[*]+/g,"$1[\\s\\S]*")}function v(a,b){b=b||e;if(-1===a.indexOf("."))return b[a];a=a.split(".");
b=b[a.shift()];return v(a.join("."),b)}function w(a,b){b=parseInt(b,10);return 0<b?[a,1E3*b]:a}function F(a,b){var c=a;void 0===c&&(c=!0);return MediaStreamTrack&&MediaStreamTrack.getSources?(MediaStreamTrack.getSources(n.rules.conditionCallback(function(a){var g;for(g=0;g<a.length;g++)if(a[g].kind===b||void 0===b){c=!0;break}return c})),"ASYNC"):c}function x(a,b){var c=0,d=0,g,s,m,y=null,l=null,e=null;a&&(c=a.ri,d=a.ci,e=a.checkTimeout,l=a.conditionTimeout);try{if(t.notActive()){for(;c<k.length;){if(!0!==
k[c].skip){for(g=k[c].conditions;d<g.length;){s=g[d];if(t[s[0]]){void 0!==b?(m=b,b=void 0):m=t[s[0]].apply(n,s.slice(1));if("[object Array]"===Object.prototype.toString.apply(m)){if(null===l||m[1]>l)l=m[1];m=m[0]}if("ASYNC"===m){f.checkerState={ri:c,ci:d,conditionTimeout:l,checkTimeout:e};p(k[c].name+": async cond '"+s[0]+"("+s.slice(1)+")'"+(l?" "+l:""));break}if(!m){p(k[c].name+": NON match '"+s[0]+"("+s.slice(1)+")'"+(l?" "+l:""));break}p(k[c].name+":     match '"+s[0]+"("+s.slice(1)+")'"+(l?" "+
l:""))}else{h('unknown conditionName "'+s[0]+'". Skipping Rule "'+k[c].name+'"');break}d++}if(d===g.length){y=k[c];break}else if(void 0!==f.checkerState)break;d=0;if(l){if(null===e||l<e)e=l;l=null}else k[c].skip=!0}else p(k[c].name+": skipped");c++}null!==y?(h("matching rule: "+y.name),n.rules.startProactiveAction(y)):void 0!==f.checkerState?p("waiting for async callback"):0<e?(e=Math.max(e,1E3),h("NO matching rule. Next check() in "+e/1E3+" sec"),z=setTimeout(x,e)):h("NO matching rule. stop.")}}catch(H){h(H)}}
var n=q&&q.NM||{},f={},t={},k=[],z=null,B,C;q&&(q.NM=n);B=function(a){function b(c,b){var h;(h=f[m+c])&&a.clearTimeout(h);delete f[m+c];f[e+c]=function(){delete f[e+c]};if(!b)f[e+c]();h=d.getElementById(g+c);h.parentNode.removeChild(h)}var c=0,d=a.document,g="nmjsonp_",e="cb_",m="cbt_",f={};a.NM.jsonp=f;return function(l){l=l||{};var h=null,k=c++,n=d.createElement("script"),q=l.url,p=l.data||{},r="",t=l.timeout||5E3,u=l.ontimeout||l.onerror;"function"===typeof l.onsuccess&&(f[e+k]=function(a){b(k);
l.onsuccess(a)});"function"===typeof l.onerror&&(n.onerror=function(){b(k);l.onerror(!1)});"function"===typeof u&&(f[m+k]=a.setTimeout(function(){var a=void 0!==f[m+k];b(k,!0);a&&u(!0)},t));p.cbf="NM.jsonp."+e+k;for(h in p)p.hasOwnProperty(h)&&(r+=(r?"&":"?")+encodeURIComponent(h)+"="+encodeURIComponent(p[h]));n.id=g+k;n.type="text/javascript";n.async=!0;n.src=q+r;d.getElementsByTagName("script")[0].parentNode.appendChild(n)}}(e);C=function(){function a(){var a=!1,d;for(d=0;d<b.length;d++)try{a=b[d]();
break}catch(g){}return a}var b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Msxml2.XMLHTTP.6.0")},function(){return new ActiveXObject("Msxml2.XMLHTTP.3.0")},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];return function(c){c=c||{};var b=c.url,g=c.method||"GET",e=c.async||!0,f=c.data||{},h=c.timeout||5E3,l=c.ontimeout||c.onerror,k=a();if(k)k.open(g,
b,e),k.onreadystatechange=function(){if(4==this.readyState)if(200<=this.status&&300>this.status)c.onsuccess(this.responseText);else if("function"===typeof c.onerror)c.onerror(!1)},k.timeout=h,k.ontimeout=function(){"function"===typeof l&&l(!0)},k.send("GET"===g?null:f);else if("function"===typeof c.onerror)c.onerror(!1)}}();t={urlMatch:function(){var a;try{for(a=0;a<arguments.length;a++)try{if(0===e.location.href.search(new RegExp(E(arguments[a]),"i")))return!0}catch(b){h(b)}}catch(c){h(c)}return!1},
referrerMatch:function(){var a;try{for(a=0;a<arguments.length;a++)try{if(e.document.referrer&&0===e.document.referrer.search(new RegExp(E(arguments[a]),"i")))return!0}catch(b){h(b)}}catch(c){h(c)}return!1},chatAvailable:function(a,b){return a?(/\.jsp$/.test(f.apiURL)?B({url:f.apiURL,data:{action:"STATUS",json:'{"category":"'+a+'"}'},onsuccess:n.rules.conditionCallback(function(a){return w(!!a.status,b)}),onerror:n.rules.conditionCallback(function(b){h("ERROR"+(b?" (timed out)":"")+" getting STATUS for category: "+
a);return!1})}):C({url:f.apiURL+"/status?category="+a,method:"GET",onsuccess:function(a){n.rules.conditionCallback(function(a){return w(!!a.available,b)})(JSON.parse(a))},onerror:function(b){h("ERROR"+(b?" (timed out)":"")+" getting STATUS for category: "+a)}}),"ASYNC"):!1},supportsWebRTC:function(){return!!(navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.getUserMedia)&&!!(e.webkitRTCPeerConnection||e.mozRTCPeerConnection||e.RTCPeerConnection)},hasMicrophone:function(a){return F(a,
"audio")},hasCamera:function(a){return F(a,"video")},timeSinceLoad:function(a){var b=(new Date).getTime(),c=b-1E3*a>=f.tsLoad;return c?c:[c,f.tsLoad+1E3*a-b]},timeSinceVisit:function(a){var b=(new Date).getTime(),c=b-1E3*a>=f.tsVisit;return c?c:[c,f.tsVisit+1E3*a-b]},isWeekday:function(a){var b=new Date,c;a:{c=arguments;var d=b.getDay(),g;if(c.contains)c=c.contains(d);else{for(g=0;g<c.length;g++)if(c[g]===d){c=!0;break a}c=!1}}return!c&&(d=new Date,d.setDate(b.getDate()+1),d.setMilliseconds(0),d.setSeconds(0),
d.setMinutes(0),d.setHours(0),d=d.getTime()-b.getTime(),36E5>d)?[c,d.getTime()-b.getTime()]:c},checkFunction:function(a,b,c){b=(new Function("return ["+b+"];"))();try{return w(!!v(a).apply(e,b),c)}catch(d){h(d)}},checkVar:function(a,b,c,d){a=v(a);var g=!1;switch(b){case "=":case "==":g=String(a)===c;break;case ">=":g=String(a)>=c;break;case ">":g=String(a)>c;break;case "<":g=String(a)<c;break;case "<=":g=String(a)<=c;break;case "!=":g=String(a)!==c}return w(g,d)},notActive:function(){return!f.isActive},
dayTime:function(a,b,c){var d,g,e,f,h=new Date;-1!=a.toString().indexOf("=")&&(a=a.split("=")[1]);d=6E4*h.getTimezoneOffset()-a;h.setTime(h.getTime()+d);for(f=1;f<arguments.length;f+=2)if(d=new Date(h.getTime()),g=new Date(h.getTime()),e=arguments[f].split(":"),d.setHours(e[0]),d.setMinutes(e[1]),d.setSeconds(0),e=arguments[f+1].split(":"),g.setHours(e[0]),g.setMinutes(e[1]),g.setSeconds(0),d<=h&&h<=g)return!0;return!1},newVisitor:function(){return!t.minVisits(2)},recurringVisitor:function(){return!t.newVisitor()},
minVisits:function(a){return f.visits>=a},maxOffers:function(a){return f.offers<a}};n.rules={init:function(a){a=a||{};f.debug=a.debug||!1;f.log=f.debug||a.log||void 0===a.log;f.tsLoad=(new Date).getTime();f.tsVisit=n.rules.initVisit();f.visits=u("nm.rules.vc")||0;f.offers=u("nm.rules.oc")||0;f.apiURL=a.apiURL||a.jspURL||"JSPClient.jsp";G(t,a.customConditions||{});a.customRules?(k=a.customRules,x()):(k=[],n.rules.loadRules(a.frontendID,k,x))},loadRules:function(a,b,c){var d;/\.jsp$/.test(f.apiURL)?
(d=f.apiURL,B({url:d,method:"GET",data:{action:"RULES",json:'{"feid":"'+a+'"}'},onsuccess:function(d){Array.prototype.push.apply(b,d);p("loaded "+b.length+" rule(s) for frontendID "+a);c()},onerror:function(b){h("ERROR"+(b?" (timed out)":"")+' loading rules for frontendID "'+a+'" from URL: '+d)}})):window.XMLHttpRequest&&(d=f.apiURL+"/frontends/"+a+"/rules",C({url:d,method:"GET",onsuccess:function(d){Array.prototype.push.apply(b,JSON.parse(d).rules);p("loaded "+b.length+" rule(s) for frontendID "+
a);c()},onerror:function(b){h("ERROR"+(b?" (timed out)":"")+' loading rules for frontendID "'+a+'" from URL: '+d)}}))},initVisit:function(a){var b=u("nm.rules.vts");null!==b&&(b=parseInt(b,10));return null===b||a||(new Date).getTime()-72E5>b?(n.rules.resetOffers(),D("nm.rules.vc"),A("nm.rules.vts",f.tsLoad)):b},resetOffers:function(){A("nm.rules.oc",0)},stopChecker:function(){z&&(clearTimeout(z),z=null)},startProactiveAction:function(a){var b=a.action;a=a.template;f.isActive=!0;b&&"[object Array]"===
Object.prototype.toString.apply(b)&&0<b.length&&v(b[0]).apply(e,b.slice(1));if(a&&"string"===typeof a){var b=f,c=e.document,d=c.body,g=c.createElement("DIV"),k=null,m,n;try{for(g.innerHTML=a;0<g.childNodes.length;)if(m=g.removeChild(g.firstChild),1===m.nodeType||3===m.nodeType)null===k&&(k=m),"SCRIPT"===m.tagName&&(n=m.text||m.innerHTML,m=c.createElement("SCRIPT"),m.type="text/javascript",void 0!==m.text?m.text=n:m.innerHTML=n),d.appendChild(m)}catch(l){h(l)}b.activeElement=k}D("nm.rules.oc")},conditionCallback:function(a){return function(){var b=
f.checkerState;delete f.checkerState;x(b,a.apply(null,arguments))}}};return n});